# Site settings
title: Oji
email: info@oji.co
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oji.co" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
